title: Thespian
author: Hugh
email: xuhui603@gmail.com
description: save me tragedy

github_username: buzzlightsaber
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: light

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
